name: Toot, together!
description: "Collaborate on Mastodon posts (toots) just like you collaborate on code, using pull requests"
author: 'Jochen Schalanda'
branding:
  icon: share-2
  color: blue
inputs:
  visibility:
    description: "The toot's visibility. Allowed values: public, unlisted, private, direct."
    required: false
    default: 'unlisted'
runs:
  using: "node24"
  main: "dist/index.js"
